shipping_methods:
  class: sfDoctrineRouteCollection
  options:
    model:                ShippingMethods
    module:               shipping_methods
    prefix_path:          shipping_methods
    column:               shippingmethodid
    with_wildcard_routes: true

genuser:
  class: sfDoctrineRouteCollection
  options:
    model:                Genuser
    module:               genuser
    prefix_path:          genuser
    column:               id
    with_wildcard_routes: true

brand:
  class: sfDoctrineRouteCollection
  options:
    model:                Brand
    module:               brand
    prefix_path:          brand
    column:               brand_id
    with_wildcard_routes: true

btwtabel:
  class: sfDoctrineRouteCollection
  options:
    model:                Btwtabel
    module:               btwtabel
    prefix_path:          btwtabel
    column:               btw_class
    with_wildcard_routes: true

categories:
  class: sfDoctrineRouteCollection
  options:
    model:                Categories
    module:               categories
    prefix_path:          categories
    column:               categoryid
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: btwtabel, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
