<?php


/**
 * This class adds structure of 'creditlimits' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:36 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CreditlimitsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CreditlimitsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CreditlimitsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CreditlimitsPeer::TABLE_NAME);
		$tMap->setPhpName('Creditlimits');
		$tMap->setClassname('Creditlimits');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('CREDITLIMIT_ID', 'CreditlimitId', 'INTEGER', true, 10);

		$tMap->addColumn('LIMIT_AMOUNT', 'LimitAmount', 'DECIMAL', true, 10);

		$tMap->addColumn('OWN_LIMIT', 'OwnLimit', 'TINYINT', true, 2);

		$tMap->addColumn('CURRENCYID', 'Currencyid', 'TINYINT', true, 2);

		$tMap->addColumn('START_DATE', 'StartDate', 'DATE', true, null);

		$tMap->addColumn('END_DATE', 'EndDate', 'DATE', true, null);

		$tMap->addColumn('CREATED', 'Created', 'TIMESTAMP', true, null);

		$tMap->addColumn('CREATED_BY', 'CreatedBy', 'INTEGER', true, 2);

		$tMap->addColumn('CONTACTID', 'Contactid', 'INTEGER', true, 10);

		$tMap->addColumn('MODIFIED', 'Modified', 'TIMESTAMP', true, null);

		$tMap->addColumn('MODIFIED_BY', 'ModifiedBy', 'INTEGER', true, 2);

		$tMap->addColumn('NOTES', 'Notes', 'VARCHAR', true, 30);

	} // doBuild()

} // CreditlimitsMapBuilder
