<?php


/**
 * This class adds structure of 'ordercost_type' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:39 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class OrdercostTypeMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.OrdercostTypeMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(OrdercostTypePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(OrdercostTypePeer::TABLE_NAME);
		$tMap->setPhpName('OrdercostType');
		$tMap->setClassname('OrdercostType');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ORDERCOSTID', 'Ordercostid', 'TINYINT', true, 2);

		$tMap->addColumn('DESCRIPTION', 'Description', 'CHAR', true, 25);

		$tMap->addColumn('WEBORDERCOST', 'Webordercost', 'FLOAT', true, null);

		$tMap->addColumn('MINWEBORDERAMOUNT', 'Minweborderamount', 'FLOAT', true, null);

		$tMap->addColumn('ORDERCOST', 'Ordercost', 'FLOAT', true, null);

		$tMap->addColumn('MINORDERAMOUNT', 'Minorderamount', 'FLOAT', true, null);

		$tMap->addColumn('SHIPPINGCOST', 'Shippingcost', 'FLOAT', true, null);

		$tMap->addColumn('REALCOST', 'Realcost', 'TINYINT', true, 3);

	} // doBuild()

} // OrdercostTypeMapBuilder
