<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOrders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orders');
        $this->hasColumn('orderid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('xp_no', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('shipvia', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('shipid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('locked_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('confirmed_yn', 'integer', 1, array('type' => 'integer', 'default' => '0', 'length' => '1'));
        $this->hasColumn('blockorder', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('endcustomer_yn', 'integer', 1, array('type' => 'integer', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('paymentterm_yn', 'integer', 1, array('type' => 'integer', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('btw_yn', 'integer', 1, array('type' => 'integer', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('price_level', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('complete_yn', 'integer', 1, array('type' => 'integer', 'default' => '0', 'length' => '1'));
        $this->hasColumn('transportcosts', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'scale' => false, 'length' => '10'));
        $this->hasColumn('manual_transportcosts', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('ordercosts', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'scale' => false, 'length' => '10'));
        $this->hasColumn('manual_ordercosts', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('employee', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('in_one_delivery_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('rma_yn', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('consignment_order', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('administration_order', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('contactid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('contactsorderid', 'string', 100, array('type' => 'string', 'length' => '100'));
        $this->hasColumn('employeeid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('orderdate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('requireddate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('shippeddate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('mailtable', 'string', 10, array('type' => 'string', 'length' => '10'));
        $this->hasColumn('shipname', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipaddress', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipcity', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipregion', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shippostalcode', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipcountry', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('comments', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('confirmed_how', 'string', 30, array('type' => 'string', 'length' => '30'));
        $this->hasColumn('trackingnummer', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}