<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseQuery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('query');
        $this->hasColumn('name', 'string', 35, array('type' => 'string', 'default' => '0', 'notnull' => true, 'length' => '35'));
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('statement', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}