<?php

/**
 * BaseFieldsTextLanguages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fieldid
 * @property integer $categoryid
 * @property integer $languageid
 * @property string $text
 * 
 * @method integer             getFieldid()    Returns the current record's "fieldid" value
 * @method integer             getCategoryid() Returns the current record's "categoryid" value
 * @method integer             getLanguageid() Returns the current record's "languageid" value
 * @method string              getText()       Returns the current record's "text" value
 * @method FieldsTextLanguages setFieldid()    Sets the current record's "fieldid" value
 * @method FieldsTextLanguages setCategoryid() Sets the current record's "categoryid" value
 * @method FieldsTextLanguages setLanguageid() Sets the current record's "languageid" value
 * @method FieldsTextLanguages setText()       Sets the current record's "text" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFieldsTextLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fields_text_languages');
        $this->hasColumn('fieldid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoryid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('languageid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('text', 'string', 50, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}