<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePaymentterm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paymentterm');
        $this->hasColumn('paymenttermid', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '1'));
        $this->hasColumn('description', 'string', 30, array('type' => 'string', 'default' => '0', 'notnull' => true, 'length' => '30'));
        $this->hasColumn('days', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '14', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('endmonth', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('incasso', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
    }

}