<?php

/**
 * BaseOrdercostType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ordercostid
 * @property string $description
 * @property float $webordercost
 * @property float $minweborderamount
 * @property float $ordercost
 * @property float $minorderamount
 * @property float $shippingcost
 * @property integer $realcost
 * 
 * @method integer       getOrdercostid()       Returns the current record's "ordercostid" value
 * @method string        getDescription()       Returns the current record's "description" value
 * @method float         getWebordercost()      Returns the current record's "webordercost" value
 * @method float         getMinweborderamount() Returns the current record's "minweborderamount" value
 * @method float         getOrdercost()         Returns the current record's "ordercost" value
 * @method float         getMinorderamount()    Returns the current record's "minorderamount" value
 * @method float         getShippingcost()      Returns the current record's "shippingcost" value
 * @method integer       getRealcost()          Returns the current record's "realcost" value
 * @method OrdercostType setOrdercostid()       Sets the current record's "ordercostid" value
 * @method OrdercostType setDescription()       Sets the current record's "description" value
 * @method OrdercostType setWebordercost()      Sets the current record's "webordercost" value
 * @method OrdercostType setMinweborderamount() Sets the current record's "minweborderamount" value
 * @method OrdercostType setOrdercost()         Sets the current record's "ordercost" value
 * @method OrdercostType setMinorderamount()    Sets the current record's "minorderamount" value
 * @method OrdercostType setShippingcost()      Sets the current record's "shippingcost" value
 * @method OrdercostType setRealcost()          Sets the current record's "realcost" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdercostType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordercost_type');
        $this->hasColumn('ordercostid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 25, array(
             'type' => 'string',
             'fixed' => 1,
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('webordercost', 'float', 6, array(
             'type' => 'float',
             'default' => '12.5',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('minweborderamount', 'float', 6, array(
             'type' => 'float',
             'default' => '300',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('ordercost', 'float', 6, array(
             'type' => 'float',
             'default' => '13.5',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('minorderamount', 'float', 6, array(
             'type' => 'float',
             'default' => '400',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('shippingcost', 'float', 6, array(
             'type' => 'float',
             'default' => '5',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('realcost', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}