<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelatedProducts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('related_products');
        $this->hasColumn('productid1', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'length' => '4'));
        $this->hasColumn('productid2', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'length' => '4'));
    }

}