<?php

/**
 * BasePaymentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $dummy
 * @property string $payment_name
 * 
 * @method integer     getId()           Returns the current record's "id" value
 * @method timestamp   getDummy()        Returns the current record's "dummy" value
 * @method string      getPaymentName()  Returns the current record's "payment_name" value
 * @method PaymentType setId()           Sets the current record's "id" value
 * @method PaymentType setDummy()        Sets the current record's "dummy" value
 * @method PaymentType setPaymentName()  Sets the current record's "payment_name" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaymentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('dummy', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('payment_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}