<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOrderDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_details');
        $this->hasColumn('orderdetailsid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('orderid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('productid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('unitprice', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('unitcost', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('unitbtw', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('quantity', 'decimal', 6, array('type' => 'decimal', 'scale' => false, 'length' => '6'));
        $this->hasColumn('to_deliver', 'integer', 4, array('type' => 'integer', 'default' => '0', 'length' => '4'));
        $this->hasColumn('extended_price', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('contactid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('btw_percentage', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('cost_percentage', 'float', 2147483647, array('type' => 'float', 'default' => '0', 'notnull' => true, 'length' => '2147483647'));
        $this->hasColumn('manual_price', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('rma_actionid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('stock_owner_id', 'integer', 2, array('type' => 'integer', 'unsigned' => '1', 'default' => '802', 'notnull' => true, 'length' => '2'));
        $this->hasColumn('productname', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('productdescription', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('discount', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('serialnb', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('orderdate', 'date', 25, array('type' => 'date', 'length' => '25'));
        $this->hasColumn('custorderrowid', 'string', 10, array('type' => 'string', 'length' => '10'));
    }

}