<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContactTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact_types');
        $this->hasColumn('contacttypeid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('contacttype', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}