<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseExtraProductInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra_product_info');
        $this->hasColumn('productid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'length' => '4'));
        $this->hasColumn('best_syst_id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('backlite_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('infrarood_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('bluetooth_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('wlan_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('gsm_gprs_yn', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('accu_size', 'integer', 2, array('type' => 'integer', 'unsigned' => '1', 'length' => '2'));
        $this->hasColumn('geheugen_int', 'float', 2147483647, array('type' => 'float', 'unsigned' => '1', 'length' => '2147483647'));
        $this->hasColumn('geheugen_ext', 'float', 2147483647, array('type' => 'float', 'unsigned' => '1', 'length' => '2147483647'));
        $this->hasColumn('gewicht', 'float', 2147483647, array('type' => 'float', 'unsigned' => '1', 'default' => '0', 'length' => '2147483647'));
        $this->hasColumn('processor_snelheid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('processor_type', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('afmetingx', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('afmetingy', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('afmetingz', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('afm_schermx', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('afm_schermy', 'float', 2147483647, array('type' => 'float', 'length' => '2147483647'));
        $this->hasColumn('resolutiex', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('resolutiey', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('kleuren', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('type_aansluiting', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('accu_type_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('accu_duur', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('geheugen_slot', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}