<?php

/**
 * BaseRMA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $contacts_id
 * @property integer $productid
 * @property integer $aantal
 * @property string $sn
 * @property integer $aticle_code
 * @property integer $factuurid
 * @property timestamp $dummy
 * @property integer $state
 * @property integer $product_customer
 * @property integer $product_location
 * @property integer $product_state
 * @property integer $valid
 * @property string $customer_id
 * @property string $supplierid
 * @property date $date_in
 * @property string $reason
 * @property date $date_done
 * @property string $additional_items
 * @property string $article_name
 * @property string $webuser
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method integer   getContactsId()       Returns the current record's "contacts_id" value
 * @method integer   getProductid()        Returns the current record's "productid" value
 * @method integer   getAantal()           Returns the current record's "aantal" value
 * @method string    getSn()               Returns the current record's "sn" value
 * @method integer   getAticleCode()       Returns the current record's "aticle_code" value
 * @method integer   getFactuurid()        Returns the current record's "factuurid" value
 * @method timestamp getDummy()            Returns the current record's "dummy" value
 * @method integer   getState()            Returns the current record's "state" value
 * @method integer   getProductCustomer()  Returns the current record's "product_customer" value
 * @method integer   getProductLocation()  Returns the current record's "product_location" value
 * @method integer   getProductState()     Returns the current record's "product_state" value
 * @method integer   getValid()            Returns the current record's "valid" value
 * @method string    getCustomerId()       Returns the current record's "customer_id" value
 * @method string    getSupplierid()       Returns the current record's "supplierid" value
 * @method date      getDateIn()           Returns the current record's "date_in" value
 * @method string    getReason()           Returns the current record's "reason" value
 * @method date      getDateDone()         Returns the current record's "date_done" value
 * @method string    getAdditionalItems()  Returns the current record's "additional_items" value
 * @method string    getArticleName()      Returns the current record's "article_name" value
 * @method string    getWebuser()          Returns the current record's "webuser" value
 * @method RMA       setId()               Sets the current record's "id" value
 * @method RMA       setContactsId()       Sets the current record's "contacts_id" value
 * @method RMA       setProductid()        Sets the current record's "productid" value
 * @method RMA       setAantal()           Sets the current record's "aantal" value
 * @method RMA       setSn()               Sets the current record's "sn" value
 * @method RMA       setAticleCode()       Sets the current record's "aticle_code" value
 * @method RMA       setFactuurid()        Sets the current record's "factuurid" value
 * @method RMA       setDummy()            Sets the current record's "dummy" value
 * @method RMA       setState()            Sets the current record's "state" value
 * @method RMA       setProductCustomer()  Sets the current record's "product_customer" value
 * @method RMA       setProductLocation()  Sets the current record's "product_location" value
 * @method RMA       setProductState()     Sets the current record's "product_state" value
 * @method RMA       setValid()            Sets the current record's "valid" value
 * @method RMA       setCustomerId()       Sets the current record's "customer_id" value
 * @method RMA       setSupplierid()       Sets the current record's "supplierid" value
 * @method RMA       setDateIn()           Sets the current record's "date_in" value
 * @method RMA       setReason()           Sets the current record's "reason" value
 * @method RMA       setDateDone()         Sets the current record's "date_done" value
 * @method RMA       setAdditionalItems()  Sets the current record's "additional_items" value
 * @method RMA       setArticleName()      Sets the current record's "article_name" value
 * @method RMA       setWebuser()          Sets the current record's "webuser" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RMA');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contacts_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => 4,
             ));
        $this->hasColumn('productid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => 4,
             ));
        $this->hasColumn('aantal', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1',
             'length' => 2,
             ));
        $this->hasColumn('sn', 'string', 50, array(
             'type' => 'string',
             'default' => '0',
             'length' => 50,
             ));
        $this->hasColumn('aticle_code', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => 1,
             ));
        $this->hasColumn('factuurid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => 4,
             ));
        $this->hasColumn('dummy', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('state', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('product_customer', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('product_location', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('product_state', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('valid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('customer_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('supplierid', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('date_in', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('reason', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('date_done', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('additional_items', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('article_name', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('webuser', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}