<?php

/**
 * BasePaymentterm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $paymenttermid
 * @property string $description
 * @property integer $days
 * @property integer $endmonth
 * @property integer $incasso
 * 
 * @method integer     getPaymenttermid() Returns the current record's "paymenttermid" value
 * @method string      getDescription()   Returns the current record's "description" value
 * @method integer     getDays()          Returns the current record's "days" value
 * @method integer     getEndmonth()      Returns the current record's "endmonth" value
 * @method integer     getIncasso()       Returns the current record's "incasso" value
 * @method Paymentterm setPaymenttermid() Sets the current record's "paymenttermid" value
 * @method Paymentterm setDescription()   Sets the current record's "description" value
 * @method Paymentterm setDays()          Sets the current record's "days" value
 * @method Paymentterm setEndmonth()      Sets the current record's "endmonth" value
 * @method Paymentterm setIncasso()       Sets the current record's "incasso" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaymentterm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paymentterm');
        $this->hasColumn('paymenttermid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 30, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('days', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '14',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('endmonth', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('incasso', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}