<?php

/**
 * BaseRMAProductLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $state_id
 * @property string $state_text
 * 
 * @method integer            getStateId()    Returns the current record's "state_id" value
 * @method string             getStateText()  Returns the current record's "state_text" value
 * @method RMAProductLocation setStateId()    Sets the current record's "state_id" value
 * @method RMAProductLocation setStateText()  Sets the current record's "state_text" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRMAProductLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RMA_product_location');
        $this->hasColumn('state_id', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('state_text', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'default' => '0',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}