<?php

/**
 * BaseCatalogus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contactid
 * @property integer $catalogusid
 * @property string $catalogusdesc
 * 
 * @method integer   getContactid()     Returns the current record's "contactid" value
 * @method integer   getCatalogusid()   Returns the current record's "catalogusid" value
 * @method string    getCatalogusdesc() Returns the current record's "catalogusdesc" value
 * @method Catalogus setContactid()     Sets the current record's "contactid" value
 * @method Catalogus setCatalogusid()   Sets the current record's "catalogusid" value
 * @method Catalogus setCatalogusdesc() Sets the current record's "catalogusdesc" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCatalogus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogus');
        $this->hasColumn('contactid', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('catalogusid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('catalogusdesc', 'string', 25, array(
             'type' => 'string',
             'fixed' => 1,
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}