<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseShippingMethods extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_methods');
        $this->hasColumn('shippingmethodid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('shippingmethod', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}