<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts');
        $this->hasColumn('contactid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('country', 'string', 2, array('type' => 'string', 'fixed' => 1, 'length' => '2'));
        $this->hasColumn('languageid', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('use_btw', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('paymentterm', 'integer', 1, array('type' => 'integer', 'default' => '4', 'length' => '1'));
        $this->hasColumn('paymentterm_margin', 'integer', 1, array('type' => 'integer', 'default' => '3', 'length' => '1'));
        $this->hasColumn('contacttypeid', 'integer', 3, array('type' => 'integer', 'unsigned' => '1', 'length' => '3'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('pricelevel', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'length' => '1'));
        $this->hasColumn('ordercosts', 'integer', 1, array('type' => 'integer', 'default' => '1', 'length' => '1'));
        $this->hasColumn('transportcost', 'integer', 1, array('type' => 'integer', 'default' => '1', 'length' => '1'));
        $this->hasColumn('ordercost_type_id', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('creditlimit', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '4'));
        $this->hasColumn('warehouse_customer', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('consignment', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('invoice_copies', 'integer', 1, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('invoice_copies_iwex', 'integer', 1, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('invoice_option', 'integer', 1, array('type' => 'integer', 'default' => '0', 'length' => '1'));
        $this->hasColumn('confirm_delivery', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('companyname', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('contactfirstname', 'string', 35, array('type' => 'string', 'length' => '35'));
        $this->hasColumn('contacttussenvoegs', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('contactname', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('contacttitle', 'string', 15, array('type' => 'string', 'length' => '15'));
        $this->hasColumn('address', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('city', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('region', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('postalcode', 'string', 10, array('type' => 'string', 'length' => '10'));
        $this->hasColumn('phone', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('fax', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('mobilephone', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('email', 'string', 100, array('type' => 'string', 'length' => '100'));
        $this->hasColumn('website', 'string', 35, array('type' => 'string', 'length' => '35'));
        $this->hasColumn('kvk_number', 'string', 35, array('type' => 'string', 'length' => '35'));
        $this->hasColumn('btw_number', 'string', 35, array('type' => 'string', 'length' => '35'));
        $this->hasColumn('bankinfo', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('upsaccount', 'string', 10, array('type' => 'string', 'length' => '10'));
        $this->hasColumn('conditions_ok_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('mailing', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('dealer_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('auto_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('watersport_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('foto_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('supplier_yn', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('aanhef', 'string', 15, array('type' => 'string', 'length' => '15'));
        $this->hasColumn('phoneextention', 'string', 10, array('type' => 'string', 'length' => '10'));
        $this->hasColumn('notes', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('uid', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('pwd', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('groupid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    }

}