<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePurchaseOrders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_orders');
        $this->hasColumn('purchaseorderid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('ship_adresid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('order_currency', 'integer', 1, array('type' => 'integer', 'default' => '2', 'length' => '1'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('status', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'length' => '1'));
        $this->hasColumn('buyer_contactid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('purchaseordernumber', 'string', 100, array('type' => 'string', 'length' => '100'));
        $this->hasColumn('purchaseorderdescription', 'string', 100, array('type' => 'string', 'length' => '100'));
        $this->hasColumn('supplierid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('employeeid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('orderdate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('shipcontactid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('shipname', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipaddress', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shippostalcode', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipcity', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('shipcountry', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('daterequired', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('datepromised', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('shipdate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('shippingmethodid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('freightcharge', 'integer', 1, array('type' => 'integer', 'length' => '1'));
        $this->hasColumn('btw_yn', 'integer', 1, array('type' => 'integer', 'length' => '1'));
        $this->hasColumn('po_sent', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    }

}