<?php

/**
 * BaseActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $contactid
 * @property timestamp $dummy
 * @property timestamp $actiondate
 * @property string $contactcontents
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method integer   getContactid()       Returns the current record's "contactid" value
 * @method timestamp getDummy()           Returns the current record's "dummy" value
 * @method timestamp getActiondate()      Returns the current record's "actiondate" value
 * @method string    getContactcontents() Returns the current record's "contactcontents" value
 * @method Actions   setId()              Sets the current record's "id" value
 * @method Actions   setContactid()       Sets the current record's "contactid" value
 * @method Actions   setDummy()           Sets the current record's "dummy" value
 * @method Actions   setActiondate()      Sets the current record's "actiondate" value
 * @method Actions   setContactcontents() Sets the current record's "contactcontents" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actions');
        $this->hasColumn('id', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('contactid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('dummy', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('actiondate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('contactcontents', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}