<?php

/**
 * BaseOrderHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $orderhistoryid
 * @property integer $orderid
 * @property integer $employee
 * @property string $old_value
 * @property string $new_value
 * @property timestamp $date_updated_at
 * @property string $fieldname
 * 
 * @method integer      getOrderhistoryid()  Returns the current record's "orderhistoryid" value
 * @method integer      getOrderid()         Returns the current record's "orderid" value
 * @method integer      getEmployee()        Returns the current record's "employee" value
 * @method string       getOldValue()        Returns the current record's "old_value" value
 * @method string       getNewValue()        Returns the current record's "new_value" value
 * @method timestamp    getDateUpdatedAt()   Returns the current record's "date_updated_at" value
 * @method string       getFieldname()       Returns the current record's "fieldname" value
 * @method OrderHistory setOrderhistoryid()  Sets the current record's "orderhistoryid" value
 * @method OrderHistory setOrderid()         Sets the current record's "orderid" value
 * @method OrderHistory setEmployee()        Sets the current record's "employee" value
 * @method OrderHistory setOldValue()        Sets the current record's "old_value" value
 * @method OrderHistory setNewValue()        Sets the current record's "new_value" value
 * @method OrderHistory setDateUpdatedAt()   Sets the current record's "date_updated_at" value
 * @method OrderHistory setFieldname()       Sets the current record's "fieldname" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_history');
        $this->hasColumn('orderhistoryid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('orderid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('old_value', 'string', 100, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('new_value', 'string', 100, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('fieldname', 'string', 25, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}