<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RMA');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('contacts_id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('productid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('aantal', 'integer', 2, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'length' => '2'));
        $this->hasColumn('sn', 'string', 50, array('type' => 'string', 'default' => '0', 'length' => '50'));
        $this->hasColumn('aticle_code', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('factuurid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('state', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('product_customer', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('product_location', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('product_state', 'integer', 1, array('type' => 'integer', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('valid', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
        $this->hasColumn('customer_id', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('supplierid', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('date_in', 'date', 25, array('type' => 'date', 'length' => '25'));
        $this->hasColumn('reason', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('date_done', 'date', 25, array('type' => 'date', 'length' => '25'));
        $this->hasColumn('additional_items', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('article_name', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('webuser', 'string', 30, array('type' => 'string', 'length' => '30'));
    }

}