<?php

/**
 * BaseInvoicesCall
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $invoices_call_id
 * @property integer $invoiceid
 * @property integer $callid
 * @property integer $typeid
 * @property integer $dispuutid
 * 
 * @method integer      getInvoicesCallId()   Returns the current record's "invoices_call_id" value
 * @method integer      getInvoiceid()        Returns the current record's "invoiceid" value
 * @method integer      getCallid()           Returns the current record's "callid" value
 * @method integer      getTypeid()           Returns the current record's "typeid" value
 * @method integer      getDispuutid()        Returns the current record's "dispuutid" value
 * @method InvoicesCall setInvoicesCallId()   Sets the current record's "invoices_call_id" value
 * @method InvoicesCall setInvoiceid()        Sets the current record's "invoiceid" value
 * @method InvoicesCall setCallid()           Sets the current record's "callid" value
 * @method InvoicesCall setTypeid()           Sets the current record's "typeid" value
 * @method InvoicesCall setDispuutid()        Sets the current record's "dispuutid" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvoicesCall extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invoices_call');
        $this->hasColumn('invoices_call_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('invoiceid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('callid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('typeid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('dispuutid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}