<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePaymentsLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payments_link');
        $this->hasColumn('link_id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('banktransactionid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('invoiceid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('link_amount', 'decimal', 10, array('type' => 'decimal', 'scale' => false, 'length' => '10'));
    }

}