<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('uid', 'string', 30, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '30'));
        $this->hasColumn('languageid', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('rma', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('purchase', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('stock', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('logins', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '4'));
        $this->hasColumn('login_attempts', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
        $this->hasColumn('passw_change_attempts', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
        $this->hasColumn('total_logins', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
        $this->hasColumn('contactid', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('companyname', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('pwd', 'string', 30, array('type' => 'string', 'length' => '30'));
        $this->hasColumn('email', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('last_online', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    }

}