<?php

/**
 * BaseEmployees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $employeeid
 * @property timestamp $dummy
 * @property string $login
 * @property string $pwd
 * @property string $uid
 * @property integer $groupid
 * @property integer $bankrekening
 * @property integer $girorekening
 * @property string $firstname
 * @property string $middlename
 * @property string $lastname
 * @property string $title
 * @property string $extension
 * @property string $workphone
 * @property string $homephone
 * @property string $mobilephone
 * @property string $address
 * @property string $postcode
 * @property string $city
 * @property date $birth_date
 * @property string $gender
 * @property string $passport
 * @property string $sofinumber
 * @property float $salary_month
 * @property date $start
 * @property date $end
 * @property float $afstand_km
 * 
 * @method integer   getEmployeeid()   Returns the current record's "employeeid" value
 * @method timestamp getDummy()        Returns the current record's "dummy" value
 * @method string    getLogin()        Returns the current record's "login" value
 * @method string    getPwd()          Returns the current record's "pwd" value
 * @method string    getUid()          Returns the current record's "uid" value
 * @method integer   getGroupid()      Returns the current record's "groupid" value
 * @method integer   getBankrekening() Returns the current record's "bankrekening" value
 * @method integer   getGirorekening() Returns the current record's "girorekening" value
 * @method string    getFirstname()    Returns the current record's "firstname" value
 * @method string    getMiddlename()   Returns the current record's "middlename" value
 * @method string    getLastname()     Returns the current record's "lastname" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method string    getExtension()    Returns the current record's "extension" value
 * @method string    getWorkphone()    Returns the current record's "workphone" value
 * @method string    getHomephone()    Returns the current record's "homephone" value
 * @method string    getMobilephone()  Returns the current record's "mobilephone" value
 * @method string    getAddress()      Returns the current record's "address" value
 * @method string    getPostcode()     Returns the current record's "postcode" value
 * @method string    getCity()         Returns the current record's "city" value
 * @method date      getBirthDate()    Returns the current record's "birth_date" value
 * @method string    getGender()       Returns the current record's "gender" value
 * @method string    getPassport()     Returns the current record's "passport" value
 * @method string    getSofinumber()   Returns the current record's "sofinumber" value
 * @method float     getSalaryMonth()  Returns the current record's "salary_month" value
 * @method date      getStart()        Returns the current record's "start" value
 * @method date      getEnd()          Returns the current record's "end" value
 * @method float     getAfstandKm()    Returns the current record's "afstand_km" value
 * @method Employees setEmployeeid()   Sets the current record's "employeeid" value
 * @method Employees setDummy()        Sets the current record's "dummy" value
 * @method Employees setLogin()        Sets the current record's "login" value
 * @method Employees setPwd()          Sets the current record's "pwd" value
 * @method Employees setUid()          Sets the current record's "uid" value
 * @method Employees setGroupid()      Sets the current record's "groupid" value
 * @method Employees setBankrekening() Sets the current record's "bankrekening" value
 * @method Employees setGirorekening() Sets the current record's "girorekening" value
 * @method Employees setFirstname()    Sets the current record's "firstname" value
 * @method Employees setMiddlename()   Sets the current record's "middlename" value
 * @method Employees setLastname()     Sets the current record's "lastname" value
 * @method Employees setTitle()        Sets the current record's "title" value
 * @method Employees setExtension()    Sets the current record's "extension" value
 * @method Employees setWorkphone()    Sets the current record's "workphone" value
 * @method Employees setHomephone()    Sets the current record's "homephone" value
 * @method Employees setMobilephone()  Sets the current record's "mobilephone" value
 * @method Employees setAddress()      Sets the current record's "address" value
 * @method Employees setPostcode()     Sets the current record's "postcode" value
 * @method Employees setCity()         Sets the current record's "city" value
 * @method Employees setBirthDate()    Sets the current record's "birth_date" value
 * @method Employees setGender()       Sets the current record's "gender" value
 * @method Employees setPassport()     Sets the current record's "passport" value
 * @method Employees setSofinumber()   Sets the current record's "sofinumber" value
 * @method Employees setSalaryMonth()  Sets the current record's "salary_month" value
 * @method Employees setStart()        Sets the current record's "start" value
 * @method Employees setEnd()          Sets the current record's "end" value
 * @method Employees setAfstandKm()    Sets the current record's "afstand_km" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('employees');
        $this->hasColumn('employeeid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('dummy', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('login', 'string', 25, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('pwd', 'string', 25, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('uid', 'string', 25, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('groupid', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('bankrekening', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('girorekening', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('firstname', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('middlename', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('lastname', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('extension', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('workphone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('homephone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobilephone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('postcode', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('birth_date', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('gender', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('passport', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('sofinumber', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('salary_month', 'float', 6, array(
             'type' => 'float',
             'length' => 6,
             ));
        $this->hasColumn('start', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('end', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('afstand_km', 'float', 6, array(
             'type' => 'float',
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}