<?php

/**
 * BaseText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $textid
 * @property integer $categoryid
 * @property integer $languageid
 * @property string $subject
 * @property string $text
 * 
 * @method integer getTextid()     Returns the current record's "textid" value
 * @method integer getCategoryid() Returns the current record's "categoryid" value
 * @method integer getLanguageid() Returns the current record's "languageid" value
 * @method string  getSubject()    Returns the current record's "subject" value
 * @method string  getText()       Returns the current record's "text" value
 * @method Text    setTextid()     Sets the current record's "textid" value
 * @method Text    setCategoryid() Sets the current record's "categoryid" value
 * @method Text    setLanguageid() Sets the current record's "languageid" value
 * @method Text    setSubject()    Sets the current record's "subject" value
 * @method Text    setText()       Sets the current record's "text" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('text');
        $this->hasColumn('textid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoryid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('languageid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('subject', 'string', 30, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('text', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}