<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actions');
        $this->hasColumn('id', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '1'));
        $this->hasColumn('contactid', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
        $this->hasColumn('dummy', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('actiondate', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('contactcontents', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    }

}