<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGuestbook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guestbook');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('entrydate', 'timestamp', 25, array('type' => 'timestamp', 'default' => '0000-00-00 00:00:00', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('comment', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
    }

}