<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('languages');
        $this->hasColumn('languageid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('language', 'string', 50, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '50'));
    }

}