<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseListbox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listbox');
        $this->hasColumn('id', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '1'));
        $this->hasColumn('value', 'string', 25, array('type' => 'string', 'default' => '0', 'length' => '25'));
        $this->hasColumn('category', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
        $this->hasColumn('text', 'string', 25, array('type' => 'string', 'length' => '25'));
        $this->hasColumn('comments', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('color', 'string', 10, array('type' => 'string', 'length' => '10'));
    }

}