<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOrderMargin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_margin');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('orderid', 'integer', 4, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('sales_value', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('purchase_value', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
        $this->hasColumn('shipping_cost', 'decimal', 10, array('type' => 'decimal', 'default' => '0.00', 'notnull' => true, 'scale' => false, 'length' => '10'));
    }

}