<?php

/**
 * BaseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $location
 * @property integer $walk_order
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method string   getLocation()   Returns the current record's "location" value
 * @method integer  getWalkOrder()  Returns the current record's "walk_order" value
 * @method Location setId()         Sets the current record's "id" value
 * @method Location setLocation()   Sets the current record's "location" value
 * @method Location setWalkOrder()  Sets the current record's "walk_order" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('location', 'string', 20, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('walk_order', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '50',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}