<?php

/**
 * BaseProductStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_stock_id
 * @property integer $product_id
 * @property integer $stock
 * @property integer $free_stock
 * @property timestamp $free_stock_calculated
 * @property integer $location_id
 * @property integer $owner_id
 * 
 * @method integer      getProductStockId()        Returns the current record's "product_stock_id" value
 * @method integer      getProductId()             Returns the current record's "product_id" value
 * @method integer      getStock()                 Returns the current record's "stock" value
 * @method integer      getFreeStock()             Returns the current record's "free_stock" value
 * @method timestamp    getFreeStockCalculated()   Returns the current record's "free_stock_calculated" value
 * @method integer      getLocationId()            Returns the current record's "location_id" value
 * @method integer      getOwnerId()               Returns the current record's "owner_id" value
 * @method ProductStock setProductStockId()        Sets the current record's "product_stock_id" value
 * @method ProductStock setProductId()             Sets the current record's "product_id" value
 * @method ProductStock setStock()                 Sets the current record's "stock" value
 * @method ProductStock setFreeStock()             Sets the current record's "free_stock" value
 * @method ProductStock setFreeStockCalculated()   Sets the current record's "free_stock_calculated" value
 * @method ProductStock setLocationId()            Sets the current record's "location_id" value
 * @method ProductStock setOwnerId()               Sets the current record's "owner_id" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductStock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_stock');
        $this->hasColumn('product_stock_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('stock', 'integer', 2, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('free_stock', 'integer', 2, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('free_stock_calculated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('location_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1080',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('owner_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '802',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}