<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('statusid', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('statustext', 'string', 40, array('type' => 'string', 'default' => '0', 'length' => '40'));
        $this->hasColumn('category', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
    }

}