<?php

/**
 * BaseEventQuerys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $taskid
 * @property integer $queryid
 * 
 * @method integer     getTaskid()  Returns the current record's "taskid" value
 * @method integer     getQueryid() Returns the current record's "queryid" value
 * @method EventQuerys setTaskid()  Sets the current record's "taskid" value
 * @method EventQuerys setQueryid() Sets the current record's "queryid" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventQuerys extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_querys');
        $this->hasColumn('taskid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('queryid', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}