<?php

/**
 * BaseCatalogusdetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $productid
 * @property integer $catalogusid
 * 
 * @method integer          getProductid()   Returns the current record's "productid" value
 * @method integer          getCatalogusid() Returns the current record's "catalogusid" value
 * @method Catalogusdetails setProductid()   Sets the current record's "productid" value
 * @method Catalogusdetails setCatalogusid() Sets the current record's "catalogusid" value
 * 
 * @package    andrea
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCatalogusdetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogusdetails');
        $this->hasColumn('productid', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('catalogusid', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}