prod:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=pumiwex;host=localhost
      username:   root
      password:   mmzoellinger
      encoding:   utf8
      persistent: true
      pooling:    true


all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=andrea;host=localhost
      username:   root
      password:   mmzoellinger
      encoding:   utf8
      persistent: true
      pooling:    true
