dev:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=andrea;host=localhost
      username:   root
      password:   mmzoellinger
      encoding:   utf8
      persistent: true
      pooling:    true

test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=andrea;host=localhost
      username:   root
      password:   mmzoellinger
      encoding:   utf8
      persistent: true
      pooling:    true

prod:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=pumiwex;host=localhost
      username:   sylvia
      password:   appel
      encoding:   utf8
      persistent: true
      pooling:    true
all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=andrea;host=localhost
      username:   root
      password:   mmzoellinger
      encoding:   utf8
      persistent: true
      pooling:    true
