<?php

/**
 * Base class that represents a row from the 'user_options' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:41 2009
 *
 * @package    lib.model.om
 */
abstract class BaseUserOptions extends BaseObject  implements Persistent {


  const PEER = 'UserOptionsPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserOptionsPeer
	 */
	protected static $peer;

	/**
	 * The value for the user_options_id field.
	 * @var        int
	 */
	protected $user_options_id;

	/**
	 * The value for the userid field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $userid;

	/**
	 * The value for the brancheadmin field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $brancheadmin;

	/**
	 * The value for the rma field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rma;

	/**
	 * The value for the purchase field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $purchase;

	/**
	 * The value for the stock field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock;

	/**
	 * The value for the catalogus field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $catalogus;

	/**
	 * The value for the add_users field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $add_users;

	/**
	 * The value for the retail_price field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $retail_price;

	/**
	 * The value for the warehouseprice field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $warehouseprice;

	/**
	 * The value for the template field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $template;

	/**
	 * The value for the rights field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rights;

	/**
	 * The value for the margins field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $margins;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUserOptions object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->userid = 0;
		$this->brancheadmin = 0;
		$this->rma = 0;
		$this->purchase = 0;
		$this->stock = 0;
		$this->catalogus = 0;
		$this->add_users = 0;
		$this->retail_price = 0;
		$this->warehouseprice = 0;
		$this->template = 0;
		$this->rights = 0;
		$this->margins = 0;
	}

	/**
	 * Get the [user_options_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserOptionsId()
	{
		return $this->user_options_id;
	}

	/**
	 * Get the [userid] column value.
	 * 
	 * @return     int
	 */
	public function getUserid()
	{
		return $this->userid;
	}

	/**
	 * Get the [brancheadmin] column value.
	 * 
	 * @return     int
	 */
	public function getBrancheadmin()
	{
		return $this->brancheadmin;
	}

	/**
	 * Get the [rma] column value.
	 * 
	 * @return     int
	 */
	public function getRma()
	{
		return $this->rma;
	}

	/**
	 * Get the [purchase] column value.
	 * 
	 * @return     int
	 */
	public function getPurchase()
	{
		return $this->purchase;
	}

	/**
	 * Get the [stock] column value.
	 * 
	 * @return     int
	 */
	public function getStock()
	{
		return $this->stock;
	}

	/**
	 * Get the [catalogus] column value.
	 * 
	 * @return     int
	 */
	public function getCatalogus()
	{
		return $this->catalogus;
	}

	/**
	 * Get the [add_users] column value.
	 * 
	 * @return     int
	 */
	public function getAddUsers()
	{
		return $this->add_users;
	}

	/**
	 * Get the [retail_price] column value.
	 * 
	 * @return     int
	 */
	public function getRetailPrice()
	{
		return $this->retail_price;
	}

	/**
	 * Get the [warehouseprice] column value.
	 * 
	 * @return     int
	 */
	public function getWarehouseprice()
	{
		return $this->warehouseprice;
	}

	/**
	 * Get the [template] column value.
	 * 
	 * @return     int
	 */
	public function getTemplate()
	{
		return $this->template;
	}

	/**
	 * Get the [rights] column value.
	 * 
	 * @return     int
	 */
	public function getRights()
	{
		return $this->rights;
	}

	/**
	 * Get the [margins] column value.
	 * 
	 * @return     int
	 */
	public function getMargins()
	{
		return $this->margins;
	}

	/**
	 * Set the value of [user_options_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setUserOptionsId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_options_id !== $v) {
			$this->user_options_id = $v;
			$this->modifiedColumns[] = UserOptionsPeer::USER_OPTIONS_ID;
		}

		return $this;
	} // setUserOptionsId()

	/**
	 * Set the value of [userid] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setUserid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->userid !== $v || $v === 0) {
			$this->userid = $v;
			$this->modifiedColumns[] = UserOptionsPeer::USERID;
		}

		return $this;
	} // setUserid()

	/**
	 * Set the value of [brancheadmin] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setBrancheadmin($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->brancheadmin !== $v || $v === 0) {
			$this->brancheadmin = $v;
			$this->modifiedColumns[] = UserOptionsPeer::BRANCHEADMIN;
		}

		return $this;
	} // setBrancheadmin()

	/**
	 * Set the value of [rma] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setRma($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rma !== $v || $v === 0) {
			$this->rma = $v;
			$this->modifiedColumns[] = UserOptionsPeer::RMA;
		}

		return $this;
	} // setRma()

	/**
	 * Set the value of [purchase] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setPurchase($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->purchase !== $v || $v === 0) {
			$this->purchase = $v;
			$this->modifiedColumns[] = UserOptionsPeer::PURCHASE;
		}

		return $this;
	} // setPurchase()

	/**
	 * Set the value of [stock] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setStock($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock !== $v || $v === 0) {
			$this->stock = $v;
			$this->modifiedColumns[] = UserOptionsPeer::STOCK;
		}

		return $this;
	} // setStock()

	/**
	 * Set the value of [catalogus] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setCatalogus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->catalogus !== $v || $v === 0) {
			$this->catalogus = $v;
			$this->modifiedColumns[] = UserOptionsPeer::CATALOGUS;
		}

		return $this;
	} // setCatalogus()

	/**
	 * Set the value of [add_users] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setAddUsers($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->add_users !== $v || $v === 0) {
			$this->add_users = $v;
			$this->modifiedColumns[] = UserOptionsPeer::ADD_USERS;
		}

		return $this;
	} // setAddUsers()

	/**
	 * Set the value of [retail_price] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setRetailPrice($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->retail_price !== $v || $v === 0) {
			$this->retail_price = $v;
			$this->modifiedColumns[] = UserOptionsPeer::RETAIL_PRICE;
		}

		return $this;
	} // setRetailPrice()

	/**
	 * Set the value of [warehouseprice] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setWarehouseprice($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->warehouseprice !== $v || $v === 0) {
			$this->warehouseprice = $v;
			$this->modifiedColumns[] = UserOptionsPeer::WAREHOUSEPRICE;
		}

		return $this;
	} // setWarehouseprice()

	/**
	 * Set the value of [template] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setTemplate($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->template !== $v || $v === 0) {
			$this->template = $v;
			$this->modifiedColumns[] = UserOptionsPeer::TEMPLATE;
		}

		return $this;
	} // setTemplate()

	/**
	 * Set the value of [rights] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setRights($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rights !== $v || $v === 0) {
			$this->rights = $v;
			$this->modifiedColumns[] = UserOptionsPeer::RIGHTS;
		}

		return $this;
	} // setRights()

	/**
	 * Set the value of [margins] column.
	 * 
	 * @param      int $v new value
	 * @return     UserOptions The current object (for fluent API support)
	 */
	public function setMargins($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->margins !== $v || $v === 0) {
			$this->margins = $v;
			$this->modifiedColumns[] = UserOptionsPeer::MARGINS;
		}

		return $this;
	} // setMargins()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UserOptionsPeer::USERID,UserOptionsPeer::BRANCHEADMIN,UserOptionsPeer::RMA,UserOptionsPeer::PURCHASE,UserOptionsPeer::STOCK,UserOptionsPeer::CATALOGUS,UserOptionsPeer::ADD_USERS,UserOptionsPeer::RETAIL_PRICE,UserOptionsPeer::WAREHOUSEPRICE,UserOptionsPeer::TEMPLATE,UserOptionsPeer::RIGHTS,UserOptionsPeer::MARGINS))) {
				return false;
			}

			if ($this->userid !== 0) {
				return false;
			}

			if ($this->brancheadmin !== 0) {
				return false;
			}

			if ($this->rma !== 0) {
				return false;
			}

			if ($this->purchase !== 0) {
				return false;
			}

			if ($this->stock !== 0) {
				return false;
			}

			if ($this->catalogus !== 0) {
				return false;
			}

			if ($this->add_users !== 0) {
				return false;
			}

			if ($this->retail_price !== 0) {
				return false;
			}

			if ($this->warehouseprice !== 0) {
				return false;
			}

			if ($this->template !== 0) {
				return false;
			}

			if ($this->rights !== 0) {
				return false;
			}

			if ($this->margins !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->user_options_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->userid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->brancheadmin = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->rma = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->purchase = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->stock = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->catalogus = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->add_users = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->retail_price = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->warehouseprice = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->template = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->rights = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->margins = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = UserOptionsPeer::NUM_COLUMNS - UserOptionsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating UserOptions object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserOptionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserOptionsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserOptions:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserOptionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserOptionsPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUserOptions:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserOptions:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserOptionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUserOptions:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserOptionsPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserOptionsPeer::USER_OPTIONS_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserOptionsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUserOptionsId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserOptionsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UserOptionsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserOptionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUserOptionsId();
				break;
			case 1:
				return $this->getUserid();
				break;
			case 2:
				return $this->getBrancheadmin();
				break;
			case 3:
				return $this->getRma();
				break;
			case 4:
				return $this->getPurchase();
				break;
			case 5:
				return $this->getStock();
				break;
			case 6:
				return $this->getCatalogus();
				break;
			case 7:
				return $this->getAddUsers();
				break;
			case 8:
				return $this->getRetailPrice();
				break;
			case 9:
				return $this->getWarehouseprice();
				break;
			case 10:
				return $this->getTemplate();
				break;
			case 11:
				return $this->getRights();
				break;
			case 12:
				return $this->getMargins();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserOptionsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUserOptionsId(),
			$keys[1] => $this->getUserid(),
			$keys[2] => $this->getBrancheadmin(),
			$keys[3] => $this->getRma(),
			$keys[4] => $this->getPurchase(),
			$keys[5] => $this->getStock(),
			$keys[6] => $this->getCatalogus(),
			$keys[7] => $this->getAddUsers(),
			$keys[8] => $this->getRetailPrice(),
			$keys[9] => $this->getWarehouseprice(),
			$keys[10] => $this->getTemplate(),
			$keys[11] => $this->getRights(),
			$keys[12] => $this->getMargins(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserOptionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUserOptionsId($value);
				break;
			case 1:
				$this->setUserid($value);
				break;
			case 2:
				$this->setBrancheadmin($value);
				break;
			case 3:
				$this->setRma($value);
				break;
			case 4:
				$this->setPurchase($value);
				break;
			case 5:
				$this->setStock($value);
				break;
			case 6:
				$this->setCatalogus($value);
				break;
			case 7:
				$this->setAddUsers($value);
				break;
			case 8:
				$this->setRetailPrice($value);
				break;
			case 9:
				$this->setWarehouseprice($value);
				break;
			case 10:
				$this->setTemplate($value);
				break;
			case 11:
				$this->setRights($value);
				break;
			case 12:
				$this->setMargins($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserOptionsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUserOptionsId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBrancheadmin($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setRma($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPurchase($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setStock($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCatalogus($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setAddUsers($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setRetailPrice($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setWarehouseprice($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTemplate($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setRights($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setMargins($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserOptionsPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserOptionsPeer::USER_OPTIONS_ID)) $criteria->add(UserOptionsPeer::USER_OPTIONS_ID, $this->user_options_id);
		if ($this->isColumnModified(UserOptionsPeer::USERID)) $criteria->add(UserOptionsPeer::USERID, $this->userid);
		if ($this->isColumnModified(UserOptionsPeer::BRANCHEADMIN)) $criteria->add(UserOptionsPeer::BRANCHEADMIN, $this->brancheadmin);
		if ($this->isColumnModified(UserOptionsPeer::RMA)) $criteria->add(UserOptionsPeer::RMA, $this->rma);
		if ($this->isColumnModified(UserOptionsPeer::PURCHASE)) $criteria->add(UserOptionsPeer::PURCHASE, $this->purchase);
		if ($this->isColumnModified(UserOptionsPeer::STOCK)) $criteria->add(UserOptionsPeer::STOCK, $this->stock);
		if ($this->isColumnModified(UserOptionsPeer::CATALOGUS)) $criteria->add(UserOptionsPeer::CATALOGUS, $this->catalogus);
		if ($this->isColumnModified(UserOptionsPeer::ADD_USERS)) $criteria->add(UserOptionsPeer::ADD_USERS, $this->add_users);
		if ($this->isColumnModified(UserOptionsPeer::RETAIL_PRICE)) $criteria->add(UserOptionsPeer::RETAIL_PRICE, $this->retail_price);
		if ($this->isColumnModified(UserOptionsPeer::WAREHOUSEPRICE)) $criteria->add(UserOptionsPeer::WAREHOUSEPRICE, $this->warehouseprice);
		if ($this->isColumnModified(UserOptionsPeer::TEMPLATE)) $criteria->add(UserOptionsPeer::TEMPLATE, $this->template);
		if ($this->isColumnModified(UserOptionsPeer::RIGHTS)) $criteria->add(UserOptionsPeer::RIGHTS, $this->rights);
		if ($this->isColumnModified(UserOptionsPeer::MARGINS)) $criteria->add(UserOptionsPeer::MARGINS, $this->margins);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserOptionsPeer::DATABASE_NAME);

		$criteria->add(UserOptionsPeer::USER_OPTIONS_ID, $this->user_options_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUserOptionsId();
	}

	/**
	 * Generic method to set the primary key (user_options_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUserOptionsId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of UserOptions (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserid($this->userid);

		$copyObj->setBrancheadmin($this->brancheadmin);

		$copyObj->setRma($this->rma);

		$copyObj->setPurchase($this->purchase);

		$copyObj->setStock($this->stock);

		$copyObj->setCatalogus($this->catalogus);

		$copyObj->setAddUsers($this->add_users);

		$copyObj->setRetailPrice($this->retail_price);

		$copyObj->setWarehouseprice($this->warehouseprice);

		$copyObj->setTemplate($this->template);

		$copyObj->setRights($this->rights);

		$copyObj->setMargins($this->margins);


		$copyObj->setNew(true);

		$copyObj->setUserOptionsId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     UserOptions Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserOptionsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserOptionsPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUserOptions:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUserOptions::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUserOptions
