<?php

/**
 * Base class that represents a row from the 'temp_inv_transactions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:40 2009
 *
 * @package    lib.model.om
 */
abstract class BaseTempInvTransactions extends BaseObject  implements Persistent {


  const PEER = 'TempInvTransactionsPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TempInvTransactionsPeer
	 */
	protected static $peer;

	/**
	 * The value for the transactionid field.
	 * @var        int
	 */
	protected $transactionid;

	/**
	 * The value for the transactiondate field.
	 * @var        string
	 */
	protected $transactiondate;

	/**
	 * The value for the productid field.
	 * @var        int
	 */
	protected $productid;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the orderid field.
	 * @var        int
	 */
	protected $orderid;

	/**
	 * The value for the orderdetailsid field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $orderdetailsid;

	/**
	 * The value for the shipmentid field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $shipmentid;

	/**
	 * The value for the unitprice field.
	 * @var        string
	 */
	protected $unitprice;

	/**
	 * The value for the unitssold field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $unitssold;

	/**
	 * The value for the btw_percentage field.
	 * Note: this column has a database default value of: '0.00'
	 * @var        string
	 */
	protected $btw_percentage;

	/**
	 * The value for the added_cost field.
	 * Note: this column has a database default value of: 0
	 * @var        double
	 */
	protected $added_cost;

	/**
	 * The value for the box_id field.
	 * @var        int
	 */
	protected $box_id;

	/**
	 * The value for the employee field.
	 * @var        int
	 */
	protected $employee;

	/**
	 * The value for the stock_owner_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock_owner_id;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTempInvTransactions object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->orderdetailsid = 0;
		$this->shipmentid = 0;
		$this->unitssold = 0;
		$this->btw_percentage = '0.00';
		$this->added_cost = 0;
		$this->stock_owner_id = 0;
	}

	/**
	 * Get the [transactionid] column value.
	 * 
	 * @return     int
	 */
	public function getTransactionid()
	{
		return $this->transactionid;
	}

	/**
	 * Get the [optionally formatted] temporal [transactiondate] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getTransactiondate($format = 'Y-m-d H:i:s')
	{
		if ($this->transactiondate === null) {
			return null;
		}


		if ($this->transactiondate === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->transactiondate);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->transactiondate, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [productid] column value.
	 * 
	 * @return     int
	 */
	public function getProductid()
	{
		return $this->productid;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [orderid] column value.
	 * 
	 * @return     int
	 */
	public function getOrderid()
	{
		return $this->orderid;
	}

	/**
	 * Get the [orderdetailsid] column value.
	 * 
	 * @return     int
	 */
	public function getOrderdetailsid()
	{
		return $this->orderdetailsid;
	}

	/**
	 * Get the [shipmentid] column value.
	 * 
	 * @return     int
	 */
	public function getShipmentid()
	{
		return $this->shipmentid;
	}

	/**
	 * Get the [unitprice] column value.
	 * 
	 * @return     string
	 */
	public function getUnitprice()
	{
		return $this->unitprice;
	}

	/**
	 * Get the [unitssold] column value.
	 * 
	 * @return     int
	 */
	public function getUnitssold()
	{
		return $this->unitssold;
	}

	/**
	 * Get the [btw_percentage] column value.
	 * 
	 * @return     string
	 */
	public function getBtwPercentage()
	{
		return $this->btw_percentage;
	}

	/**
	 * Get the [added_cost] column value.
	 * 
	 * @return     double
	 */
	public function getAddedCost()
	{
		return $this->added_cost;
	}

	/**
	 * Get the [box_id] column value.
	 * 
	 * @return     int
	 */
	public function getBoxId()
	{
		return $this->box_id;
	}

	/**
	 * Get the [employee] column value.
	 * 
	 * @return     int
	 */
	public function getEmployee()
	{
		return $this->employee;
	}

	/**
	 * Get the [stock_owner_id] column value.
	 * 
	 * @return     int
	 */
	public function getStockOwnerId()
	{
		return $this->stock_owner_id;
	}

	/**
	 * Set the value of [transactionid] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setTransactionid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->transactionid !== $v) {
			$this->transactionid = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::TRANSACTIONID;
		}

		return $this;
	} // setTransactionid()

	/**
	 * Sets the value of [transactiondate] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setTransactiondate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->transactiondate !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->transactiondate !== null && $tmpDt = new DateTime($this->transactiondate)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->transactiondate = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TempInvTransactionsPeer::TRANSACTIONDATE;
			}
		} // if either are not null

		return $this;
	} // setTransactiondate()

	/**
	 * Set the value of [productid] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setProductid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->productid !== $v) {
			$this->productid = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::PRODUCTID;
		}

		return $this;
	} // setProductid()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [orderid] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setOrderid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->orderid !== $v) {
			$this->orderid = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::ORDERID;
		}

		return $this;
	} // setOrderid()

	/**
	 * Set the value of [orderdetailsid] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setOrderdetailsid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->orderdetailsid !== $v || $v === 0) {
			$this->orderdetailsid = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::ORDERDETAILSID;
		}

		return $this;
	} // setOrderdetailsid()

	/**
	 * Set the value of [shipmentid] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setShipmentid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->shipmentid !== $v || $v === 0) {
			$this->shipmentid = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::SHIPMENTID;
		}

		return $this;
	} // setShipmentid()

	/**
	 * Set the value of [unitprice] column.
	 * 
	 * @param      string $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setUnitprice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->unitprice !== $v) {
			$this->unitprice = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::UNITPRICE;
		}

		return $this;
	} // setUnitprice()

	/**
	 * Set the value of [unitssold] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setUnitssold($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->unitssold !== $v || $v === 0) {
			$this->unitssold = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::UNITSSOLD;
		}

		return $this;
	} // setUnitssold()

	/**
	 * Set the value of [btw_percentage] column.
	 * 
	 * @param      string $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setBtwPercentage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->btw_percentage !== $v || $v === '0.00') {
			$this->btw_percentage = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::BTW_PERCENTAGE;
		}

		return $this;
	} // setBtwPercentage()

	/**
	 * Set the value of [added_cost] column.
	 * 
	 * @param      double $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setAddedCost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->added_cost !== $v || $v === 0) {
			$this->added_cost = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::ADDED_COST;
		}

		return $this;
	} // setAddedCost()

	/**
	 * Set the value of [box_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setBoxId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->box_id !== $v) {
			$this->box_id = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::BOX_ID;
		}

		return $this;
	} // setBoxId()

	/**
	 * Set the value of [employee] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setEmployee($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->employee !== $v) {
			$this->employee = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::EMPLOYEE;
		}

		return $this;
	} // setEmployee()

	/**
	 * Set the value of [stock_owner_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TempInvTransactions The current object (for fluent API support)
	 */
	public function setStockOwnerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock_owner_id !== $v || $v === 0) {
			$this->stock_owner_id = $v;
			$this->modifiedColumns[] = TempInvTransactionsPeer::STOCK_OWNER_ID;
		}

		return $this;
	} // setStockOwnerId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(TempInvTransactionsPeer::ORDERDETAILSID,TempInvTransactionsPeer::SHIPMENTID,TempInvTransactionsPeer::UNITSSOLD,TempInvTransactionsPeer::BTW_PERCENTAGE,TempInvTransactionsPeer::ADDED_COST,TempInvTransactionsPeer::STOCK_OWNER_ID))) {
				return false;
			}

			if ($this->orderdetailsid !== 0) {
				return false;
			}

			if ($this->shipmentid !== 0) {
				return false;
			}

			if ($this->unitssold !== 0) {
				return false;
			}

			if ($this->btw_percentage !== '0.00') {
				return false;
			}

			if ($this->added_cost !== 0) {
				return false;
			}

			if ($this->stock_owner_id !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->transactionid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->transactiondate = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->productid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->description = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->orderid = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->orderdetailsid = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->shipmentid = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->unitprice = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->unitssold = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->btw_percentage = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->added_cost = ($row[$startcol + 10] !== null) ? (double) $row[$startcol + 10] : null;
			$this->box_id = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->employee = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->stock_owner_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = TempInvTransactionsPeer::NUM_COLUMNS - TempInvTransactionsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating TempInvTransactions object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TempInvTransactionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TempInvTransactionsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTempInvTransactions:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TempInvTransactionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			TempInvTransactionsPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTempInvTransactions:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTempInvTransactions:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TempInvTransactionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTempInvTransactions:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			TempInvTransactionsPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TempInvTransactionsPeer::TRANSACTIONID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TempInvTransactionsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setTransactionid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TempInvTransactionsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = TempInvTransactionsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TempInvTransactionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getTransactionid();
				break;
			case 1:
				return $this->getTransactiondate();
				break;
			case 2:
				return $this->getProductid();
				break;
			case 3:
				return $this->getDescription();
				break;
			case 4:
				return $this->getOrderid();
				break;
			case 5:
				return $this->getOrderdetailsid();
				break;
			case 6:
				return $this->getShipmentid();
				break;
			case 7:
				return $this->getUnitprice();
				break;
			case 8:
				return $this->getUnitssold();
				break;
			case 9:
				return $this->getBtwPercentage();
				break;
			case 10:
				return $this->getAddedCost();
				break;
			case 11:
				return $this->getBoxId();
				break;
			case 12:
				return $this->getEmployee();
				break;
			case 13:
				return $this->getStockOwnerId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TempInvTransactionsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getTransactionid(),
			$keys[1] => $this->getTransactiondate(),
			$keys[2] => $this->getProductid(),
			$keys[3] => $this->getDescription(),
			$keys[4] => $this->getOrderid(),
			$keys[5] => $this->getOrderdetailsid(),
			$keys[6] => $this->getShipmentid(),
			$keys[7] => $this->getUnitprice(),
			$keys[8] => $this->getUnitssold(),
			$keys[9] => $this->getBtwPercentage(),
			$keys[10] => $this->getAddedCost(),
			$keys[11] => $this->getBoxId(),
			$keys[12] => $this->getEmployee(),
			$keys[13] => $this->getStockOwnerId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TempInvTransactionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setTransactionid($value);
				break;
			case 1:
				$this->setTransactiondate($value);
				break;
			case 2:
				$this->setProductid($value);
				break;
			case 3:
				$this->setDescription($value);
				break;
			case 4:
				$this->setOrderid($value);
				break;
			case 5:
				$this->setOrderdetailsid($value);
				break;
			case 6:
				$this->setShipmentid($value);
				break;
			case 7:
				$this->setUnitprice($value);
				break;
			case 8:
				$this->setUnitssold($value);
				break;
			case 9:
				$this->setBtwPercentage($value);
				break;
			case 10:
				$this->setAddedCost($value);
				break;
			case 11:
				$this->setBoxId($value);
				break;
			case 12:
				$this->setEmployee($value);
				break;
			case 13:
				$this->setStockOwnerId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TempInvTransactionsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setTransactionid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTransactiondate($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProductid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescription($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setOrderid($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setOrderdetailsid($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setShipmentid($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUnitprice($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUnitssold($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setBtwPercentage($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAddedCost($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setBoxId($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setEmployee($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setStockOwnerId($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TempInvTransactionsPeer::DATABASE_NAME);

		if ($this->isColumnModified(TempInvTransactionsPeer::TRANSACTIONID)) $criteria->add(TempInvTransactionsPeer::TRANSACTIONID, $this->transactionid);
		if ($this->isColumnModified(TempInvTransactionsPeer::TRANSACTIONDATE)) $criteria->add(TempInvTransactionsPeer::TRANSACTIONDATE, $this->transactiondate);
		if ($this->isColumnModified(TempInvTransactionsPeer::PRODUCTID)) $criteria->add(TempInvTransactionsPeer::PRODUCTID, $this->productid);
		if ($this->isColumnModified(TempInvTransactionsPeer::DESCRIPTION)) $criteria->add(TempInvTransactionsPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(TempInvTransactionsPeer::ORDERID)) $criteria->add(TempInvTransactionsPeer::ORDERID, $this->orderid);
		if ($this->isColumnModified(TempInvTransactionsPeer::ORDERDETAILSID)) $criteria->add(TempInvTransactionsPeer::ORDERDETAILSID, $this->orderdetailsid);
		if ($this->isColumnModified(TempInvTransactionsPeer::SHIPMENTID)) $criteria->add(TempInvTransactionsPeer::SHIPMENTID, $this->shipmentid);
		if ($this->isColumnModified(TempInvTransactionsPeer::UNITPRICE)) $criteria->add(TempInvTransactionsPeer::UNITPRICE, $this->unitprice);
		if ($this->isColumnModified(TempInvTransactionsPeer::UNITSSOLD)) $criteria->add(TempInvTransactionsPeer::UNITSSOLD, $this->unitssold);
		if ($this->isColumnModified(TempInvTransactionsPeer::BTW_PERCENTAGE)) $criteria->add(TempInvTransactionsPeer::BTW_PERCENTAGE, $this->btw_percentage);
		if ($this->isColumnModified(TempInvTransactionsPeer::ADDED_COST)) $criteria->add(TempInvTransactionsPeer::ADDED_COST, $this->added_cost);
		if ($this->isColumnModified(TempInvTransactionsPeer::BOX_ID)) $criteria->add(TempInvTransactionsPeer::BOX_ID, $this->box_id);
		if ($this->isColumnModified(TempInvTransactionsPeer::EMPLOYEE)) $criteria->add(TempInvTransactionsPeer::EMPLOYEE, $this->employee);
		if ($this->isColumnModified(TempInvTransactionsPeer::STOCK_OWNER_ID)) $criteria->add(TempInvTransactionsPeer::STOCK_OWNER_ID, $this->stock_owner_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TempInvTransactionsPeer::DATABASE_NAME);

		$criteria->add(TempInvTransactionsPeer::TRANSACTIONID, $this->transactionid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getTransactionid();
	}

	/**
	 * Generic method to set the primary key (transactionid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setTransactionid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of TempInvTransactions (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTransactiondate($this->transactiondate);

		$copyObj->setProductid($this->productid);

		$copyObj->setDescription($this->description);

		$copyObj->setOrderid($this->orderid);

		$copyObj->setOrderdetailsid($this->orderdetailsid);

		$copyObj->setShipmentid($this->shipmentid);

		$copyObj->setUnitprice($this->unitprice);

		$copyObj->setUnitssold($this->unitssold);

		$copyObj->setBtwPercentage($this->btw_percentage);

		$copyObj->setAddedCost($this->added_cost);

		$copyObj->setBoxId($this->box_id);

		$copyObj->setEmployee($this->employee);

		$copyObj->setStockOwnerId($this->stock_owner_id);


		$copyObj->setNew(true);

		$copyObj->setTransactionid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     TempInvTransactions Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TempInvTransactionsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TempInvTransactionsPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTempInvTransactions:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTempInvTransactions::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTempInvTransactions
