<?php

/**
 * Base static class for performing query and update operations on the 'orders' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:39 2009
 *
 * @package    lib.model.om
 */
abstract class BaseOrdersPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'orders';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Orders';

	/** The total number of columns. */
	const NUM_COLUMNS = 37;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ORDERID field */
	const ORDERID = 'orders.ORDERID';

	/** the column name for the CONTACTID field */
	const CONTACTID = 'orders.CONTACTID';

	/** the column name for the CONTACTSORDERID field */
	const CONTACTSORDERID = 'orders.CONTACTSORDERID';

	/** the column name for the EMPLOYEEID field */
	const EMPLOYEEID = 'orders.EMPLOYEEID';

	/** the column name for the ORDERDATE field */
	const ORDERDATE = 'orders.ORDERDATE';

	/** the column name for the REQUIREDDATE field */
	const REQUIREDDATE = 'orders.REQUIREDDATE';

	/** the column name for the SHIPPEDDATE field */
	const SHIPPEDDATE = 'orders.SHIPPEDDATE';

	/** the column name for the XP_NO field */
	const XP_NO = 'orders.XP_NO';

	/** the column name for the MAILTABLE field */
	const MAILTABLE = 'orders.MAILTABLE';

	/** the column name for the SHIPVIA field */
	const SHIPVIA = 'orders.SHIPVIA';

	/** the column name for the SHIPID field */
	const SHIPID = 'orders.SHIPID';

	/** the column name for the SHIPNAME field */
	const SHIPNAME = 'orders.SHIPNAME';

	/** the column name for the SHIPADDRESS field */
	const SHIPADDRESS = 'orders.SHIPADDRESS';

	/** the column name for the SHIPCITY field */
	const SHIPCITY = 'orders.SHIPCITY';

	/** the column name for the SHIPREGION field */
	const SHIPREGION = 'orders.SHIPREGION';

	/** the column name for the SHIPPOSTALCODE field */
	const SHIPPOSTALCODE = 'orders.SHIPPOSTALCODE';

	/** the column name for the SHIPCOUNTRY field */
	const SHIPCOUNTRY = 'orders.SHIPCOUNTRY';

	/** the column name for the LOCKED_YN field */
	const LOCKED_YN = 'orders.LOCKED_YN';

	/** the column name for the COMMENTS field */
	const COMMENTS = 'orders.COMMENTS';

	/** the column name for the CONFIRMED_YN field */
	const CONFIRMED_YN = 'orders.CONFIRMED_YN';

	/** the column name for the BLOCKORDER field */
	const BLOCKORDER = 'orders.BLOCKORDER';

	/** the column name for the CONFIRMED_HOW field */
	const CONFIRMED_HOW = 'orders.CONFIRMED_HOW';

	/** the column name for the ENDCUSTOMER_YN field */
	const ENDCUSTOMER_YN = 'orders.ENDCUSTOMER_YN';

	/** the column name for the PAYMENTTERM_YN field */
	const PAYMENTTERM_YN = 'orders.PAYMENTTERM_YN';

	/** the column name for the TRACKINGNUMMER field */
	const TRACKINGNUMMER = 'orders.TRACKINGNUMMER';

	/** the column name for the BTW_YN field */
	const BTW_YN = 'orders.BTW_YN';

	/** the column name for the PRICE_LEVEL field */
	const PRICE_LEVEL = 'orders.PRICE_LEVEL';

	/** the column name for the COMPLETE_YN field */
	const COMPLETE_YN = 'orders.COMPLETE_YN';

	/** the column name for the TRANSPORTCOSTS field */
	const TRANSPORTCOSTS = 'orders.TRANSPORTCOSTS';

	/** the column name for the MANUAL_TRANSPORTCOSTS field */
	const MANUAL_TRANSPORTCOSTS = 'orders.MANUAL_TRANSPORTCOSTS';

	/** the column name for the ORDERCOSTS field */
	const ORDERCOSTS = 'orders.ORDERCOSTS';

	/** the column name for the MANUAL_ORDERCOSTS field */
	const MANUAL_ORDERCOSTS = 'orders.MANUAL_ORDERCOSTS';

	/** the column name for the EMPLOYEE field */
	const EMPLOYEE = 'orders.EMPLOYEE';

	/** the column name for the IN_ONE_DELIVERY_YN field */
	const IN_ONE_DELIVERY_YN = 'orders.IN_ONE_DELIVERY_YN';

	/** the column name for the RMA_YN field */
	const RMA_YN = 'orders.RMA_YN';

	/** the column name for the CONSIGNMENT_ORDER field */
	const CONSIGNMENT_ORDER = 'orders.CONSIGNMENT_ORDER';

	/** the column name for the ADMINISTRATION_ORDER field */
	const ADMINISTRATION_ORDER = 'orders.ADMINISTRATION_ORDER';

	/**
	 * An identiy map to hold any loaded instances of Orders objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Orders[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Orderid', 'Contactid', 'Contactsorderid', 'Employeeid', 'Orderdate', 'Requireddate', 'Shippeddate', 'XpNo', 'Mailtable', 'Shipvia', 'Shipid', 'Shipname', 'Shipaddress', 'Shipcity', 'Shipregion', 'Shippostalcode', 'Shipcountry', 'LockedYn', 'Comments', 'ConfirmedYn', 'Blockorder', 'ConfirmedHow', 'EndcustomerYn', 'PaymenttermYn', 'Trackingnummer', 'BtwYn', 'PriceLevel', 'CompleteYn', 'Transportcosts', 'ManualTransportcosts', 'Ordercosts', 'ManualOrdercosts', 'Employee', 'InOneDeliveryYn', 'RmaYn', 'ConsignmentOrder', 'AdministrationOrder', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('orderid', 'contactid', 'contactsorderid', 'employeeid', 'orderdate', 'requireddate', 'shippeddate', 'xpNo', 'mailtable', 'shipvia', 'shipid', 'shipname', 'shipaddress', 'shipcity', 'shipregion', 'shippostalcode', 'shipcountry', 'lockedYn', 'comments', 'confirmedYn', 'blockorder', 'confirmedHow', 'endcustomerYn', 'paymenttermYn', 'trackingnummer', 'btwYn', 'priceLevel', 'completeYn', 'transportcosts', 'manualTransportcosts', 'ordercosts', 'manualOrdercosts', 'employee', 'inOneDeliveryYn', 'rmaYn', 'consignmentOrder', 'administrationOrder', ),
		BasePeer::TYPE_COLNAME => array (self::ORDERID, self::CONTACTID, self::CONTACTSORDERID, self::EMPLOYEEID, self::ORDERDATE, self::REQUIREDDATE, self::SHIPPEDDATE, self::XP_NO, self::MAILTABLE, self::SHIPVIA, self::SHIPID, self::SHIPNAME, self::SHIPADDRESS, self::SHIPCITY, self::SHIPREGION, self::SHIPPOSTALCODE, self::SHIPCOUNTRY, self::LOCKED_YN, self::COMMENTS, self::CONFIRMED_YN, self::BLOCKORDER, self::CONFIRMED_HOW, self::ENDCUSTOMER_YN, self::PAYMENTTERM_YN, self::TRACKINGNUMMER, self::BTW_YN, self::PRICE_LEVEL, self::COMPLETE_YN, self::TRANSPORTCOSTS, self::MANUAL_TRANSPORTCOSTS, self::ORDERCOSTS, self::MANUAL_ORDERCOSTS, self::EMPLOYEE, self::IN_ONE_DELIVERY_YN, self::RMA_YN, self::CONSIGNMENT_ORDER, self::ADMINISTRATION_ORDER, ),
		BasePeer::TYPE_FIELDNAME => array ('OrderID', 'ContactID', 'ContactsOrderID', 'EmployeeID', 'OrderDate', 'RequiredDate', 'ShippedDate', 'xp_no', 'mailtable', 'ShipVia', 'ShipID', 'ShipName', 'Shipaddress', 'ShipCity', 'ShipRegion', 'ShipPostalCode', 'ShipCountry', 'Locked_yn', 'Comments', 'confirmed_yn', 'blockorder', 'Confirmed_how', 'endcustomer_yn', 'paymentterm_yn', 'Trackingnummer', 'Btw_YN', 'Price_level', 'Complete_yn', 'Transportcosts', 'manual_transportcosts', 'Ordercosts', 'manual_ordercosts', 'employee', 'in_one_delivery_yn', 'rma_yn', 'consignment_order', 'administration_order', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Orderid' => 0, 'Contactid' => 1, 'Contactsorderid' => 2, 'Employeeid' => 3, 'Orderdate' => 4, 'Requireddate' => 5, 'Shippeddate' => 6, 'XpNo' => 7, 'Mailtable' => 8, 'Shipvia' => 9, 'Shipid' => 10, 'Shipname' => 11, 'Shipaddress' => 12, 'Shipcity' => 13, 'Shipregion' => 14, 'Shippostalcode' => 15, 'Shipcountry' => 16, 'LockedYn' => 17, 'Comments' => 18, 'ConfirmedYn' => 19, 'Blockorder' => 20, 'ConfirmedHow' => 21, 'EndcustomerYn' => 22, 'PaymenttermYn' => 23, 'Trackingnummer' => 24, 'BtwYn' => 25, 'PriceLevel' => 26, 'CompleteYn' => 27, 'Transportcosts' => 28, 'ManualTransportcosts' => 29, 'Ordercosts' => 30, 'ManualOrdercosts' => 31, 'Employee' => 32, 'InOneDeliveryYn' => 33, 'RmaYn' => 34, 'ConsignmentOrder' => 35, 'AdministrationOrder' => 36, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('orderid' => 0, 'contactid' => 1, 'contactsorderid' => 2, 'employeeid' => 3, 'orderdate' => 4, 'requireddate' => 5, 'shippeddate' => 6, 'xpNo' => 7, 'mailtable' => 8, 'shipvia' => 9, 'shipid' => 10, 'shipname' => 11, 'shipaddress' => 12, 'shipcity' => 13, 'shipregion' => 14, 'shippostalcode' => 15, 'shipcountry' => 16, 'lockedYn' => 17, 'comments' => 18, 'confirmedYn' => 19, 'blockorder' => 20, 'confirmedHow' => 21, 'endcustomerYn' => 22, 'paymenttermYn' => 23, 'trackingnummer' => 24, 'btwYn' => 25, 'priceLevel' => 26, 'completeYn' => 27, 'transportcosts' => 28, 'manualTransportcosts' => 29, 'ordercosts' => 30, 'manualOrdercosts' => 31, 'employee' => 32, 'inOneDeliveryYn' => 33, 'rmaYn' => 34, 'consignmentOrder' => 35, 'administrationOrder' => 36, ),
		BasePeer::TYPE_COLNAME => array (self::ORDERID => 0, self::CONTACTID => 1, self::CONTACTSORDERID => 2, self::EMPLOYEEID => 3, self::ORDERDATE => 4, self::REQUIREDDATE => 5, self::SHIPPEDDATE => 6, self::XP_NO => 7, self::MAILTABLE => 8, self::SHIPVIA => 9, self::SHIPID => 10, self::SHIPNAME => 11, self::SHIPADDRESS => 12, self::SHIPCITY => 13, self::SHIPREGION => 14, self::SHIPPOSTALCODE => 15, self::SHIPCOUNTRY => 16, self::LOCKED_YN => 17, self::COMMENTS => 18, self::CONFIRMED_YN => 19, self::BLOCKORDER => 20, self::CONFIRMED_HOW => 21, self::ENDCUSTOMER_YN => 22, self::PAYMENTTERM_YN => 23, self::TRACKINGNUMMER => 24, self::BTW_YN => 25, self::PRICE_LEVEL => 26, self::COMPLETE_YN => 27, self::TRANSPORTCOSTS => 28, self::MANUAL_TRANSPORTCOSTS => 29, self::ORDERCOSTS => 30, self::MANUAL_ORDERCOSTS => 31, self::EMPLOYEE => 32, self::IN_ONE_DELIVERY_YN => 33, self::RMA_YN => 34, self::CONSIGNMENT_ORDER => 35, self::ADMINISTRATION_ORDER => 36, ),
		BasePeer::TYPE_FIELDNAME => array ('OrderID' => 0, 'ContactID' => 1, 'ContactsOrderID' => 2, 'EmployeeID' => 3, 'OrderDate' => 4, 'RequiredDate' => 5, 'ShippedDate' => 6, 'xp_no' => 7, 'mailtable' => 8, 'ShipVia' => 9, 'ShipID' => 10, 'ShipName' => 11, 'Shipaddress' => 12, 'ShipCity' => 13, 'ShipRegion' => 14, 'ShipPostalCode' => 15, 'ShipCountry' => 16, 'Locked_yn' => 17, 'Comments' => 18, 'confirmed_yn' => 19, 'blockorder' => 20, 'Confirmed_how' => 21, 'endcustomer_yn' => 22, 'paymentterm_yn' => 23, 'Trackingnummer' => 24, 'Btw_YN' => 25, 'Price_level' => 26, 'Complete_yn' => 27, 'Transportcosts' => 28, 'manual_transportcosts' => 29, 'Ordercosts' => 30, 'manual_ordercosts' => 31, 'employee' => 32, 'in_one_delivery_yn' => 33, 'rma_yn' => 34, 'consignment_order' => 35, 'administration_order' => 36, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new OrdersMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. OrdersPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(OrdersPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(OrdersPeer::ORDERID);

		$criteria->addSelectColumn(OrdersPeer::CONTACTID);

		$criteria->addSelectColumn(OrdersPeer::CONTACTSORDERID);

		$criteria->addSelectColumn(OrdersPeer::EMPLOYEEID);

		$criteria->addSelectColumn(OrdersPeer::ORDERDATE);

		$criteria->addSelectColumn(OrdersPeer::REQUIREDDATE);

		$criteria->addSelectColumn(OrdersPeer::SHIPPEDDATE);

		$criteria->addSelectColumn(OrdersPeer::XP_NO);

		$criteria->addSelectColumn(OrdersPeer::MAILTABLE);

		$criteria->addSelectColumn(OrdersPeer::SHIPVIA);

		$criteria->addSelectColumn(OrdersPeer::SHIPID);

		$criteria->addSelectColumn(OrdersPeer::SHIPNAME);

		$criteria->addSelectColumn(OrdersPeer::SHIPADDRESS);

		$criteria->addSelectColumn(OrdersPeer::SHIPCITY);

		$criteria->addSelectColumn(OrdersPeer::SHIPREGION);

		$criteria->addSelectColumn(OrdersPeer::SHIPPOSTALCODE);

		$criteria->addSelectColumn(OrdersPeer::SHIPCOUNTRY);

		$criteria->addSelectColumn(OrdersPeer::LOCKED_YN);

		$criteria->addSelectColumn(OrdersPeer::COMMENTS);

		$criteria->addSelectColumn(OrdersPeer::CONFIRMED_YN);

		$criteria->addSelectColumn(OrdersPeer::BLOCKORDER);

		$criteria->addSelectColumn(OrdersPeer::CONFIRMED_HOW);

		$criteria->addSelectColumn(OrdersPeer::ENDCUSTOMER_YN);

		$criteria->addSelectColumn(OrdersPeer::PAYMENTTERM_YN);

		$criteria->addSelectColumn(OrdersPeer::TRACKINGNUMMER);

		$criteria->addSelectColumn(OrdersPeer::BTW_YN);

		$criteria->addSelectColumn(OrdersPeer::PRICE_LEVEL);

		$criteria->addSelectColumn(OrdersPeer::COMPLETE_YN);

		$criteria->addSelectColumn(OrdersPeer::TRANSPORTCOSTS);

		$criteria->addSelectColumn(OrdersPeer::MANUAL_TRANSPORTCOSTS);

		$criteria->addSelectColumn(OrdersPeer::ORDERCOSTS);

		$criteria->addSelectColumn(OrdersPeer::MANUAL_ORDERCOSTS);

		$criteria->addSelectColumn(OrdersPeer::EMPLOYEE);

		$criteria->addSelectColumn(OrdersPeer::IN_ONE_DELIVERY_YN);

		$criteria->addSelectColumn(OrdersPeer::RMA_YN);

		$criteria->addSelectColumn(OrdersPeer::CONSIGNMENT_ORDER);

		$criteria->addSelectColumn(OrdersPeer::ADMINISTRATION_ORDER);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(OrdersPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			OrdersPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseOrdersPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseOrdersPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Orders
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = OrdersPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return OrdersPeer::populateObjects(OrdersPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseOrdersPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseOrdersPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			OrdersPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Orders $value A Orders object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Orders $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getOrderid();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Orders object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Orders) {
				$key = (string) $value->getOrderid();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Orders object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Orders Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = OrdersPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = OrdersPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = OrdersPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				OrdersPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return OrdersPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Orders or Criteria object.
	 *
	 * @param      mixed $values Criteria or Orders object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseOrdersPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseOrdersPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Orders object
		}

		if ($criteria->containsKey(OrdersPeer::ORDERID) && $criteria->keyContainsValue(OrdersPeer::ORDERID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.OrdersPeer::ORDERID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseOrdersPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseOrdersPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Orders or Criteria object.
	 *
	 * @param      mixed $values Criteria or Orders object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseOrdersPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseOrdersPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(OrdersPeer::ORDERID);
			$selectCriteria->add(OrdersPeer::ORDERID, $criteria->remove(OrdersPeer::ORDERID), $comparison);

		} else { // $values is Orders object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseOrdersPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseOrdersPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the orders table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(OrdersPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Orders or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Orders object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			OrdersPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Orders) {
			// invalidate the cache for this single object
			OrdersPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(OrdersPeer::ORDERID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				OrdersPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Orders object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Orders $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Orders $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(OrdersPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(OrdersPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(OrdersPeer::DATABASE_NAME, OrdersPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = OrdersPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Orders
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = OrdersPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(OrdersPeer::DATABASE_NAME);
		$criteria->add(OrdersPeer::ORDERID, $pk);

		$v = OrdersPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(OrdersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(OrdersPeer::DATABASE_NAME);
			$criteria->add(OrdersPeer::ORDERID, $pks, Criteria::IN);
			$objs = OrdersPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseOrdersPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the OrdersPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the OrdersPeer class:
//
// Propel::getDatabaseMap(OrdersPeer::DATABASE_NAME)->addTableBuilder(OrdersPeer::TABLE_NAME, OrdersPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseOrdersPeer::DATABASE_NAME)->addTableBuilder(BaseOrdersPeer::TABLE_NAME, BaseOrdersPeer::getMapBuilder());

