<?php

/**
 * Base class that represents a row from the 'Personen' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 11:52:34 2009
 *
 * @package    lib.model.om
 */
abstract class BasePersonen extends BaseObject  implements Persistent {


  const PEER = 'PersonenPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PersonenPeer
	 */
	protected static $peer;

	/**
	 * The value for the persoonid field.
	 * @var        int
	 */
	protected $persoonid;

	/**
	 * The value for the contactid field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $contactid;

	/**
	 * The value for the personen_type_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $personen_type_id;

	/**
	 * The value for the titel field.
	 * @var        string
	 */
	protected $titel;

	/**
	 * The value for the voornaam field.
	 * @var        string
	 */
	protected $voornaam;

	/**
	 * The value for the achternaam field.
	 * @var        string
	 */
	protected $achternaam;

	/**
	 * The value for the tussenvoegsel field.
	 * @var        string
	 */
	protected $tussenvoegsel;

	/**
	 * The value for the languageid field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $languageid;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the mailing_yn field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $mailing_yn;

	/**
	 * The value for the tel field.
	 * @var        string
	 */
	protected $tel;

	/**
	 * The value for the fax field.
	 * @var        string
	 */
	protected $fax;

	/**
	 * The value for the aanhef field.
	 * @var        string
	 */
	protected $aanhef;

	/**
	 * The value for the gender field.
	 * @var        int
	 */
	protected $gender;

	/**
	 * The value for the notes field.
	 * @var        string
	 */
	protected $notes;

	/**
	 * The value for the mobile field.
	 * @var        string
	 */
	protected $mobile;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePersonen object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->contactid = 0;
		$this->personen_type_id = 0;
		$this->languageid = 1;
		$this->mailing_yn = 1;
	}

	/**
	 * Get the [persoonid] column value.
	 * 
	 * @return     int
	 */
	public function getPersoonid()
	{
		return $this->persoonid;
	}

	/**
	 * Get the [contactid] column value.
	 * 
	 * @return     int
	 */
	public function getContactid()
	{
		return $this->contactid;
	}

	/**
	 * Get the [personen_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getPersonenTypeId()
	{
		return $this->personen_type_id;
	}

	/**
	 * Get the [titel] column value.
	 * 
	 * @return     string
	 */
	public function getTitel()
	{
		return $this->titel;
	}

	/**
	 * Get the [voornaam] column value.
	 * 
	 * @return     string
	 */
	public function getVoornaam()
	{
		return $this->voornaam;
	}

	/**
	 * Get the [achternaam] column value.
	 * 
	 * @return     string
	 */
	public function getAchternaam()
	{
		return $this->achternaam;
	}

	/**
	 * Get the [tussenvoegsel] column value.
	 * 
	 * @return     string
	 */
	public function getTussenvoegsel()
	{
		return $this->tussenvoegsel;
	}

	/**
	 * Get the [languageid] column value.
	 * 
	 * @return     int
	 */
	public function getLanguageid()
	{
		return $this->languageid;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [mailing_yn] column value.
	 * 
	 * @return     int
	 */
	public function getMailingYn()
	{
		return $this->mailing_yn;
	}

	/**
	 * Get the [tel] column value.
	 * 
	 * @return     string
	 */
	public function getTel()
	{
		return $this->tel;
	}

	/**
	 * Get the [fax] column value.
	 * 
	 * @return     string
	 */
	public function getFax()
	{
		return $this->fax;
	}

	/**
	 * Get the [aanhef] column value.
	 * 
	 * @return     string
	 */
	public function getAanhef()
	{
		return $this->aanhef;
	}

	/**
	 * Get the [gender] column value.
	 * 
	 * @return     int
	 */
	public function getGender()
	{
		return $this->gender;
	}

	/**
	 * Get the [notes] column value.
	 * 
	 * @return     string
	 */
	public function getNotes()
	{
		return $this->notes;
	}

	/**
	 * Get the [mobile] column value.
	 * 
	 * @return     string
	 */
	public function getMobile()
	{
		return $this->mobile;
	}

	/**
	 * Set the value of [persoonid] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setPersoonid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->persoonid !== $v) {
			$this->persoonid = $v;
			$this->modifiedColumns[] = PersonenPeer::PERSOONID;
		}

		return $this;
	} // setPersoonid()

	/**
	 * Set the value of [contactid] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setContactid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->contactid !== $v || $v === 0) {
			$this->contactid = $v;
			$this->modifiedColumns[] = PersonenPeer::CONTACTID;
		}

		return $this;
	} // setContactid()

	/**
	 * Set the value of [personen_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setPersonenTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->personen_type_id !== $v || $v === 0) {
			$this->personen_type_id = $v;
			$this->modifiedColumns[] = PersonenPeer::PERSONEN_TYPE_ID;
		}

		return $this;
	} // setPersonenTypeId()

	/**
	 * Set the value of [titel] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setTitel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titel !== $v) {
			$this->titel = $v;
			$this->modifiedColumns[] = PersonenPeer::TITEL;
		}

		return $this;
	} // setTitel()

	/**
	 * Set the value of [voornaam] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setVoornaam($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->voornaam !== $v) {
			$this->voornaam = $v;
			$this->modifiedColumns[] = PersonenPeer::VOORNAAM;
		}

		return $this;
	} // setVoornaam()

	/**
	 * Set the value of [achternaam] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setAchternaam($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->achternaam !== $v) {
			$this->achternaam = $v;
			$this->modifiedColumns[] = PersonenPeer::ACHTERNAAM;
		}

		return $this;
	} // setAchternaam()

	/**
	 * Set the value of [tussenvoegsel] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setTussenvoegsel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tussenvoegsel !== $v) {
			$this->tussenvoegsel = $v;
			$this->modifiedColumns[] = PersonenPeer::TUSSENVOEGSEL;
		}

		return $this;
	} // setTussenvoegsel()

	/**
	 * Set the value of [languageid] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setLanguageid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->languageid !== $v || $v === 1) {
			$this->languageid = $v;
			$this->modifiedColumns[] = PersonenPeer::LANGUAGEID;
		}

		return $this;
	} // setLanguageid()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = PersonenPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [mailing_yn] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setMailingYn($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mailing_yn !== $v || $v === 1) {
			$this->mailing_yn = $v;
			$this->modifiedColumns[] = PersonenPeer::MAILING_YN;
		}

		return $this;
	} // setMailingYn()

	/**
	 * Set the value of [tel] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setTel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tel !== $v) {
			$this->tel = $v;
			$this->modifiedColumns[] = PersonenPeer::TEL;
		}

		return $this;
	} // setTel()

	/**
	 * Set the value of [fax] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setFax($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fax !== $v) {
			$this->fax = $v;
			$this->modifiedColumns[] = PersonenPeer::FAX;
		}

		return $this;
	} // setFax()

	/**
	 * Set the value of [aanhef] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setAanhef($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->aanhef !== $v) {
			$this->aanhef = $v;
			$this->modifiedColumns[] = PersonenPeer::AANHEF;
		}

		return $this;
	} // setAanhef()

	/**
	 * Set the value of [gender] column.
	 * 
	 * @param      int $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setGender($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->gender !== $v) {
			$this->gender = $v;
			$this->modifiedColumns[] = PersonenPeer::GENDER;
		}

		return $this;
	} // setGender()

	/**
	 * Set the value of [notes] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setNotes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notes !== $v) {
			$this->notes = $v;
			$this->modifiedColumns[] = PersonenPeer::NOTES;
		}

		return $this;
	} // setNotes()

	/**
	 * Set the value of [mobile] column.
	 * 
	 * @param      string $v new value
	 * @return     Personen The current object (for fluent API support)
	 */
	public function setMobile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mobile !== $v) {
			$this->mobile = $v;
			$this->modifiedColumns[] = PersonenPeer::MOBILE;
		}

		return $this;
	} // setMobile()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(PersonenPeer::CONTACTID,PersonenPeer::PERSONEN_TYPE_ID,PersonenPeer::LANGUAGEID,PersonenPeer::MAILING_YN))) {
				return false;
			}

			if ($this->contactid !== 0) {
				return false;
			}

			if ($this->personen_type_id !== 0) {
				return false;
			}

			if ($this->languageid !== 1) {
				return false;
			}

			if ($this->mailing_yn !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->persoonid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->contactid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->personen_type_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->titel = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->voornaam = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->achternaam = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->tussenvoegsel = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->languageid = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->email = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->mailing_yn = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->tel = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->fax = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->aanhef = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->gender = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->notes = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->mobile = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = PersonenPeer::NUM_COLUMNS - PersonenPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Personen object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonenPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PersonenPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePersonen:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonenPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PersonenPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePersonen:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePersonen:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonenPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePersonen:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PersonenPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PersonenPeer::PERSOONID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PersonenPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setPersoonid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PersonenPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PersonenPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonenPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getPersoonid();
				break;
			case 1:
				return $this->getContactid();
				break;
			case 2:
				return $this->getPersonenTypeId();
				break;
			case 3:
				return $this->getTitel();
				break;
			case 4:
				return $this->getVoornaam();
				break;
			case 5:
				return $this->getAchternaam();
				break;
			case 6:
				return $this->getTussenvoegsel();
				break;
			case 7:
				return $this->getLanguageid();
				break;
			case 8:
				return $this->getEmail();
				break;
			case 9:
				return $this->getMailingYn();
				break;
			case 10:
				return $this->getTel();
				break;
			case 11:
				return $this->getFax();
				break;
			case 12:
				return $this->getAanhef();
				break;
			case 13:
				return $this->getGender();
				break;
			case 14:
				return $this->getNotes();
				break;
			case 15:
				return $this->getMobile();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PersonenPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getPersoonid(),
			$keys[1] => $this->getContactid(),
			$keys[2] => $this->getPersonenTypeId(),
			$keys[3] => $this->getTitel(),
			$keys[4] => $this->getVoornaam(),
			$keys[5] => $this->getAchternaam(),
			$keys[6] => $this->getTussenvoegsel(),
			$keys[7] => $this->getLanguageid(),
			$keys[8] => $this->getEmail(),
			$keys[9] => $this->getMailingYn(),
			$keys[10] => $this->getTel(),
			$keys[11] => $this->getFax(),
			$keys[12] => $this->getAanhef(),
			$keys[13] => $this->getGender(),
			$keys[14] => $this->getNotes(),
			$keys[15] => $this->getMobile(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonenPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setPersoonid($value);
				break;
			case 1:
				$this->setContactid($value);
				break;
			case 2:
				$this->setPersonenTypeId($value);
				break;
			case 3:
				$this->setTitel($value);
				break;
			case 4:
				$this->setVoornaam($value);
				break;
			case 5:
				$this->setAchternaam($value);
				break;
			case 6:
				$this->setTussenvoegsel($value);
				break;
			case 7:
				$this->setLanguageid($value);
				break;
			case 8:
				$this->setEmail($value);
				break;
			case 9:
				$this->setMailingYn($value);
				break;
			case 10:
				$this->setTel($value);
				break;
			case 11:
				$this->setFax($value);
				break;
			case 12:
				$this->setAanhef($value);
				break;
			case 13:
				$this->setGender($value);
				break;
			case 14:
				$this->setNotes($value);
				break;
			case 15:
				$this->setMobile($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PersonenPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setPersoonid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setContactid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPersonenTypeId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitel($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setVoornaam($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setAchternaam($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTussenvoegsel($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setLanguageid($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setEmail($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setMailingYn($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTel($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setFax($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setAanhef($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setGender($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setNotes($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setMobile($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PersonenPeer::DATABASE_NAME);

		if ($this->isColumnModified(PersonenPeer::PERSOONID)) $criteria->add(PersonenPeer::PERSOONID, $this->persoonid);
		if ($this->isColumnModified(PersonenPeer::CONTACTID)) $criteria->add(PersonenPeer::CONTACTID, $this->contactid);
		if ($this->isColumnModified(PersonenPeer::PERSONEN_TYPE_ID)) $criteria->add(PersonenPeer::PERSONEN_TYPE_ID, $this->personen_type_id);
		if ($this->isColumnModified(PersonenPeer::TITEL)) $criteria->add(PersonenPeer::TITEL, $this->titel);
		if ($this->isColumnModified(PersonenPeer::VOORNAAM)) $criteria->add(PersonenPeer::VOORNAAM, $this->voornaam);
		if ($this->isColumnModified(PersonenPeer::ACHTERNAAM)) $criteria->add(PersonenPeer::ACHTERNAAM, $this->achternaam);
		if ($this->isColumnModified(PersonenPeer::TUSSENVOEGSEL)) $criteria->add(PersonenPeer::TUSSENVOEGSEL, $this->tussenvoegsel);
		if ($this->isColumnModified(PersonenPeer::LANGUAGEID)) $criteria->add(PersonenPeer::LANGUAGEID, $this->languageid);
		if ($this->isColumnModified(PersonenPeer::EMAIL)) $criteria->add(PersonenPeer::EMAIL, $this->email);
		if ($this->isColumnModified(PersonenPeer::MAILING_YN)) $criteria->add(PersonenPeer::MAILING_YN, $this->mailing_yn);
		if ($this->isColumnModified(PersonenPeer::TEL)) $criteria->add(PersonenPeer::TEL, $this->tel);
		if ($this->isColumnModified(PersonenPeer::FAX)) $criteria->add(PersonenPeer::FAX, $this->fax);
		if ($this->isColumnModified(PersonenPeer::AANHEF)) $criteria->add(PersonenPeer::AANHEF, $this->aanhef);
		if ($this->isColumnModified(PersonenPeer::GENDER)) $criteria->add(PersonenPeer::GENDER, $this->gender);
		if ($this->isColumnModified(PersonenPeer::NOTES)) $criteria->add(PersonenPeer::NOTES, $this->notes);
		if ($this->isColumnModified(PersonenPeer::MOBILE)) $criteria->add(PersonenPeer::MOBILE, $this->mobile);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PersonenPeer::DATABASE_NAME);

		$criteria->add(PersonenPeer::PERSOONID, $this->persoonid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getPersoonid();
	}

	/**
	 * Generic method to set the primary key (persoonid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setPersoonid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Personen (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setContactid($this->contactid);

		$copyObj->setPersonenTypeId($this->personen_type_id);

		$copyObj->setTitel($this->titel);

		$copyObj->setVoornaam($this->voornaam);

		$copyObj->setAchternaam($this->achternaam);

		$copyObj->setTussenvoegsel($this->tussenvoegsel);

		$copyObj->setLanguageid($this->languageid);

		$copyObj->setEmail($this->email);

		$copyObj->setMailingYn($this->mailing_yn);

		$copyObj->setTel($this->tel);

		$copyObj->setFax($this->fax);

		$copyObj->setAanhef($this->aanhef);

		$copyObj->setGender($this->gender);

		$copyObj->setNotes($this->notes);

		$copyObj->setMobile($this->mobile);


		$copyObj->setNew(true);

		$copyObj->setPersoonid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Personen Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PersonenPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PersonenPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePersonen:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePersonen::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePersonen
